#include "Keywords.h"

const std::vector<KeywordInfo> KEYWORDS =
{
	// types
	{CbTokenType::TYPE_FLAT, "flat", WordBoundary::BOTH},
	{CbTokenType::TYPE_SHARP, "sharp", WordBoundary::BOTH},
	{CbTokenType::TYPE_DEGREE, "degree", WordBoundary::BOTH},
	{CbTokenType::TYPE_FREQ, "freq", WordBoundary::BOTH},
	{CbTokenType::TYPE_NOTE, "char", WordBoundary::BOTH},
	{CbTokenType::TYPE_MUTE, "mute", WordBoundary::BOTH},
	{CbTokenType::TYPE_BAR, "bar", WordBoundary::BOTH},
	{CbTokenType::TYPE_RIFF, "riff", WordBoundary::BOTH},
	{CbTokenType::TYPE_FERMATA, "fermata", WordBoundary::BOTH},

	// keywords
	{CbTokenType::KEYWORD_UNISON, "unison", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_BASS, "bass", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_INSTRUMENT, "instrument", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_PLAYERSCORE, "player score", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_CONDUCTORSCORE, "conductor score", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_SECTIONSCORE, "section score", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_TUTTI, "tutti", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_SORDINO, "sordino", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_SECTION, "section", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_PAUSE, "pause", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_RESUME, "resume", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_PLAY, "play", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_PLAYBAR, "play bar", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_HEAR, "hear", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_SWITCH, "A", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_RETURN, "B", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_CASE, "C", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_IF, "D", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_ELSE, "E", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_FMAJ, "Fmaj", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_FMIN, "Fmin", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_WHILE, "G", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_SONG, "song", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_FEAT, "feat.", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_MOTIF, "motif", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_REST, "rest", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_VARIATION, "variation", WordBoundary::BOTH},
	{CbTokenType::KEYWORD_CTOR_CALL, "𝆫", WordBoundary::NONE},
	{CbTokenType::KEYWORD_C_CLEF, "𝄡", WordBoundary::NONE},

	// punctuation
	{CbTokenType::PUNCTUATION_RET_TYPE_ARROW, "𝅘𝅥=", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_COMMA, ",", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_COPYRIGHT, "©", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_OPEN_SQUARE_BRACE, "[", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_CLOSE_SQUARE_BRACE, "]", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_OPEN_CURLY_BRACKET, "𝄋", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_CLOSE_CURLY_BRACKET, "𝄌", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_PARENTHESIS_OPEN, "𝄕", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_PARENTHESIS_CLOSE, "𝄇", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_COLON, ":", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_BACKSLASH, "𝄍", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_REST, "𝄽", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_OPEN_LINE, "𝄞", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_SEMICOLON, "𝄀", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_CLOSE_FUNC, "𝄂", WordBoundary::NONE},
	{CbTokenType::PUNCTUATION_NEW_LINE, "\n", WordBoundary::NONE},

	// unary operations
	{CbTokenType::UNARY_OP_SHARP, "♯", WordBoundary::AFTER},
	{CbTokenType::UNARY_OP_DOUBLE_SHARP, "𝄪", WordBoundary::AFTER},
	{CbTokenType::UNARY_OP_FLAT, "♭", WordBoundary::AFTER},
	{CbTokenType::UNARY_OP_DOUBLE_FLAT, "𝄫", WordBoundary::AFTER},
	{CbTokenType::UNARY_OP_NOT, "!", WordBoundary::AFTER},
	{CbTokenType::UNARY_OP_NATRUAL, "♮", WordBoundary::AFTER},

	// binary operation
	{CbTokenType::BINARY_OP_EQUIAL, "=", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_NOT_EQUAL, "!=", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_LESSER_EQUAL, "<=", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_GREATER_EQUAL, ">=", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_LESS_THAN, "<", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_MORE_THAN, ">", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_PLUS, "+", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_MINUS, "-", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_DIVIDE, "/", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_MULTIPLY, "*", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_MODULO, "%", WordBoundary::NONE},
	{CbTokenType::BINARY_OP_OR, "div.", WordBoundary::BOTH},
	{CbTokenType::BINARY_OP_AND, "non div.", WordBoundary::BOTH},

	// assignment operations
	{CbTokenType::ASSIGNMENT_OP_EQUAL, "=", WordBoundary::BOTH},
	{CbTokenType::ASSIGNMENT_OP_PLUS_EQUAL, "+=", WordBoundary::BOTH},
	{CbTokenType::ASSIGNMENT_OP_MINUS_EQUAL, "-=", WordBoundary::BOTH},
	{CbTokenType::ASSIGNMENT_OP_DIVIDE_EQUAL, "/=", WordBoundary::BOTH},
	{CbTokenType::ASSIGNMENT_OP_MULTIPLY_EQUAL, "*=", WordBoundary::BOTH},
	{CbTokenType::ASSIGNMENT_OP_MODULUS_EQUAL, "%=", WordBoundary::BOTH},

	// comments
	{CbTokenType::COMMENT_SINGLE, "?", WordBoundary::BOTH},
	{CbTokenType::COMMENT_MULTI_START, "?*", WordBoundary::BOTH},
};